2020-12-18 11:51:47,659 ERROR: Exception on /index [POST] [in /home/mahmoudodeh/Desktop/Flask/flask-venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mahmoudodeh/Desktop/Flask/flask-venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mahmoudodeh/Desktop/Flask/flask-venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mahmoudodeh/Desktop/Flask/flask-venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mahmoudodeh/Desktop/Flask/flask-venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mahmoudodeh/Desktop/Flask/flask-venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mahmoudodeh/Desktop/Flask/flask-venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mahmoudodeh/Desktop/Flask/flask-venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mahmoudodeh/Desktop/Flask/Flask-Tutorial/microblog/app/routes.py", line 34, in index
    post = Post(body=form.post.data, author=current_user)
NameError: name 'Post' is not defined
2020-12-18 11:53:26,690 INFO: Microblog startup [in /home/mahmoudodeh/Desktop/Flask/Flask-Tutorial/microblog/app/__init__.py:48]
2020-12-18 12:18:16,511 INFO: Microblog startup [in /home/mahmoudodeh/Desktop/Flask/Flask-Tutorial/microblog/app/__init__.py:48]
2020-12-18 12:18:24,127 INFO: Microblog startup [in /home/mahmoudodeh/Desktop/Flask/Flask-Tutorial/microblog/app/__init__.py:48]
2020-12-18 12:43:52,446 INFO: Microblog startup [in /home/mahmoudodeh/Desktop/Flask/Flask-Tutorial/microblog/app/__init__.py:48]
